# Lecture 9: Functions #

In [20]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Defining Functions ##  

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [21]:
def triple(x):
    return 3 * x

In [22]:
triple(4)

12

We can also assign a value to a name, and call the function on the name:

In [23]:
num = 4

In [24]:
triple(num)

12

## The Anatomy of a Function ##  
    
```python
def functionname(Arguments_Parameters_Expressions_or_Values):     
      return return_expression
```

## Functions are Type-Agnostic  ## 

In [25]:
triple('ha')

'hahaha'

In [26]:
triple(np.arange(4))

array([0, 3, 6, 9])

### Discussion ###

- What does the following function do?
- What type of input does it take?
- What type of output does it produce?
- What's a good name for the function?

```python
def f(s):     
      return np.round(s / sum(s) * 100, 2)
```

In [27]:
def percent_of_total(s):
    return np.round(s / sum(s) * 100, 2)

In [28]:
first_four=make_array(1,2,3,4)
first_four

array([1, 2, 3, 4])

In [29]:
percent_of_total(first_four)

array([ 10.,  20.,  30.,  40.])

In [30]:
percent_of_total(make_array(1, 213, 38))

array([  0.4 ,  84.52,  15.08])

### Functions Can Take Multiple Arguments ###

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

In [31]:
def hypotenuse(x, y):
    hypot_squared = (x ** 2 + y ** 2)
    hypot = hypot_squared ** 0.5
    return hypot

In [32]:
hypotenuse(1, 2)

2.23606797749979

In [33]:
hypotenuse(3, 4)

5.0

## Apply ##

In [34]:
ages = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
ages

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

In [35]:
def name_and_birthyear(name, year):
    return name + " was born in " + str(year) + "."

In [36]:
ages_and_years = ages.apply(name_and_birthyear, 'Person', 'Birth Year')
ages_and_years

array(['Jim was born in 1985.', 'Pam was born in 1988.',
       'Michael was born in 1967.', 'Creed was born in 1904.'],
      dtype='<U25')

In [37]:
ages_and_years[0]

'Jim was born in 1985.'

# Practice

1. Define a function named percent_increase that takes two inputs: small and big. The function returns the the *percent* increase from small to big. For example, if small = 100 and big = 105, then percent_increase(small, big) returns 5.

2. Apply this function to the Gross and Adjusted Gross columns of top_movies.

3. Attach this new column to the table.

In [38]:
top_movies = Table.read_table('top_movies_2017.csv').select("Title", "Gross", "Gross (Adjusted)")
top_movies

Title                            | Gross     | Gross (Adjusted)
Gone with the Wind               | 198676459 | 1796176700
Star Wars                        | 460998007 | 1583483200
The Sound of Music               | 158671368 | 1266072700
E.T.: The Extra-Terrestrial      | 435110554 | 1261085000
Titanic                          | 658672302 | 1204368000
The Ten Commandments             | 65500000  | 1164590000
Jaws                             | 260000000 | 1138620700
Doctor Zhivago                   | 111721910 | 1103564200
The Exorcist                     | 232906145 | 983226600
Snow White and the Seven Dwarves | 184925486 | 969010000
... (190 rows omitted)

In [47]:
percinc = abs(top_movies.column('Gross (Adjusted)')/top_movies.column('Gross')-1)* 100
perctable = top_movies.with_column('Percent', percinc)
perctable

Title                            | Gross     | Gross (Adjusted) | Percent
Gone with the Wind               | 198676459 | 1796176700       | 804.071
Star Wars                        | 460998007 | 1583483200       | 243.49
The Sound of Music               | 158671368 | 1266072700       | 697.921
E.T.: The Extra-Terrestrial      | 435110554 | 1261085000       | 189.831
Titanic                          | 658672302 | 1204368000       | 82.8478
The Ten Commandments             | 65500000  | 1164590000       | 1678
Jaws                             | 260000000 | 1138620700       | 337.931
Doctor Zhivago                   | 111721910 | 1103564200       | 887.778
The Exorcist                     | 232906145 | 983226600        | 322.156
Snow White and the Seven Dwarves | 184925486 | 969010000        | 424
... (190 rows omitted)

In [45]:
def percent_increase(small, big):
    ratio = big/small
    prop_increase = ratio - 1
    percent = prop_increase * 100
    return round(percent,2)
percent_increase(100,105)

5.0

In [49]:
increase_array = top_movies.apply(percent_increase,'Gross','Gross (Adjusted)')
top_movies = top_movies.with_column('percent_increase', increase_array)
top_movies

Title                            | Gross     | Gross (Adjusted) | percent_increase
Gone with the Wind               | 198676459 | 1796176700       | 804.07
Star Wars                        | 460998007 | 1583483200       | 243.49
The Sound of Music               | 158671368 | 1266072700       | 697.92
E.T.: The Extra-Terrestrial      | 435110554 | 1261085000       | 189.83
Titanic                          | 658672302 | 1204368000       | 82.85
The Ten Commandments             | 65500000  | 1164590000       | 1678
Jaws                             | 260000000 | 1138620700       | 337.93
Doctor Zhivago                   | 111721910 | 1103564200       | 887.78
The Exorcist                     | 232906145 | 983226600        | 322.16
Snow White and the Seven Dwarves | 184925486 | 969010000        | 424
... (190 rows omitted)